// Spec 7: the update banner. The desktop app injects its update script
// (internal/desktop/update_script.go) into the dashboard and serves the update
// status at /desktop/update; the web build has neither, so the spec evaluates the
// same script (generated by e2e/updatescript at global setup) once the page has
// loaded, as the desktop app does, and stubs the update endpoints with page.route().
import { readFileSync } from "node:fs";
import { type Page } from "@playwright/test";
import { UPDATE_SCRIPT_FILE } from "../paths.js";
import { expect, test } from "./fixtures.js";

interface UpdateStatus {
  current: string;
  latest: string;
  available: boolean;
  mandatory: boolean;
  installable: boolean;
  notes: string;
  html_url: string;
  state: string;
  checking: boolean;
  error: string;
  percent: number;
  action: string;
  file: string;
  legacy: { found: boolean; dir: string; state: string; error: string };
}

function release(overrides: Partial<UpdateStatus> = {}): UpdateStatus {
  return {
    current: "0.14.0",
    latest: "0.15.0",
    available: true,
    mandatory: false,
    installable: true,
    notes: "## Highlights\n- Browser tests in CI",
    html_url: "https://github.com/YigitCittan/mongorescue/releases/tag/v0.15.0",
    state: "idle",
    checking: false,
    error: "",
    percent: 0,
    action: "",
    file: "",
    legacy: { found: false, dir: "", state: "", error: "" },
    ...overrides,
  };
}

async function injectUpdateScript(page: Page): Promise<void> {
  await expect(page.getByRole("tablist", { name: "Sections" })).toBeVisible();
  // Evaluated like the desktop app's WindowExecJS, so the page's CSP does not apply.
  await page.evaluate(readFileSync(UPDATE_SCRIPT_FILE, "utf8"));
}

test("shows an optional update in a dismissible banner", async ({ page }) => {
  let status = release();
  const installs: (string | undefined)[] = [];
  await page.route("**/desktop/update", route => route.fulfill({ json: status }));
  await page.route("**/desktop/update/install", async route => {
    installs.push(await route.request().headerValue("X-MongoRescue-Desktop") ?? undefined);
    status = release({ state: "downloading", percent: 40 });
    await route.fulfill({ status: 202, json: status });
  });

  await page.goto("/");
  await injectUpdateScript(page);

  const banner = page.getByRole("region", { name: "Version 0.15.0 is available" });
  await expect(banner).toBeVisible();
  await expect(banner).toContainText("(you have 0.14.0)");
  await banner.getByRole("button", { name: "Release notes" }).click();
  await expect(banner.getByText("Browser tests in CI")).toBeVisible();

  // "Later" hides the banner; the header button stays and brings it back.
  await banner.getByRole("button", { name: "Later" }).click();
  await expect(banner).toBeHidden();
  const header = page.getByRole("button", { name: "Update to v0.15.0" });
  await expect(header).toBeVisible();
  await header.click();

  await expect(banner).toBeVisible();
  await expect(banner.getByRole("status")).toHaveText("Downloading the update… 40%");
  expect(installs).toEqual(["1"]);
});

test("blocks the dashboard for a mandatory update", async ({ page }) => {
  await page.route("**/desktop/update", route => route.fulfill({ json: release({ mandatory: true }) }));

  await page.goto("/");
  await injectUpdateScript(page);

  const dialog = page.getByRole("alertdialog", { name: "Update required" });
  await expect(dialog).toBeVisible();
  await expect(dialog).toContainText("Version 0.14.0 → 0.15.0");
  await expect(dialog.getByRole("button", { name: "Update now" })).toBeFocused();
  // Escape does not close it.
  await page.keyboard.press("Escape");
  await expect(dialog).toBeVisible();
});
