package encryption

import (
	"bytes"
	"crypto/sha256"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
	"testing/iotest"

	"filippo.io/age"
)

// ageChunkSize is the plaintext size of one age payload chunk.
const ageChunkSize = 64 * 1024

// TestRoundTripSizes streams payloads around the chunk boundaries through both
// modes, writing in uneven pieces and reading one byte at a time for the small ones.
func TestRoundTripSizes(t *testing.T) {
	id, r := genKey(t)
	x25519, _ := NewX25519Encryptor([]string{r})
	scrypt, err := NewScryptEncryptor("correct horse battery staple", testWorkFactor)
	if err != nil {
		t.Fatal(err)
	}
	decX, _ := NewDecryptor(DecryptorConfig{Identity: id})
	decS, _ := NewDecryptor(DecryptorConfig{Passphrase: "correct horse battery staple"})

	sizes := []int{0, 1, 15, 16, 17, ageChunkSize - 1, ageChunkSize, ageChunkSize + 1,
		2*ageChunkSize - 1, 2 * ageChunkSize, 2*ageChunkSize + 1, 5*ageChunkSize + 12345}
	for _, mode := range []struct {
		name string
		enc  *Encryptor
		dec  *Decryptor
	}{{"x25519", x25519, decX}, {"scrypt", scrypt, decS}} {
		for _, size := range sizes {
			t.Run(fmt.Sprintf("%s/%d", mode.name, size), func(t *testing.T) {
				payload := randomPayload(t, size)
				var ct bytes.Buffer
				w, err := mode.enc.Encrypt(&ct)
				if err != nil {
					t.Fatal(err)
				}
				// Uneven writes cross chunk boundaries at arbitrary offsets.
				for rest := payload; len(rest) > 0; {
					n := min(len(rest), 7919)
					if _, err = w.Write(rest[:n]); err != nil {
						t.Fatal(err)
					}
					rest = rest[n:]
				}
				if err = w.Close(); err != nil {
					t.Fatal(err)
				}

				plain, err := mode.dec.Decrypt(bytes.NewReader(ct.Bytes()))
				if err != nil {
					t.Fatalf("Decrypt: %v", err)
				}
				if size <= 2*ageChunkSize+1 {
					plain = iotest.OneByteReader(plain)
				}
				got, err := io.ReadAll(plain)
				if err != nil || !bytes.Equal(got, payload) {
					t.Fatalf("round trip of %d bytes: got %d bytes, %v", size, len(got), err)
				}

				// Every chunk adds a 16-byte tag; an empty payload still has one
				// (empty, final) chunk.
				chunks := max(1, (size+ageChunkSize-1)/ageChunkSize)
				if header := ct.Len() - size - 16*chunks - 16; header <= 0 {
					t.Fatalf("ciphertext of %d bytes for %d plaintext bytes leaves no room for the header", ct.Len(), size)
				}
			})
		}
	}
}

// patternSource yields n generated bytes and hashes them, so a large payload is
// never held in memory.
type patternSource struct {
	remaining int64
	offset    byte
	hash      io.Writer
}

func (p *patternSource) Read(b []byte) (int, error) {
	if p.remaining <= 0 {
		return 0, io.EOF
	}
	if int64(len(b)) > p.remaining {
		b = b[:p.remaining]
	}
	for i := range b {
		b[i] = p.offset
		p.offset = p.offset*31 + 7
	}
	p.remaining -= int64(len(b))
	_, _ = p.hash.Write(b)
	return len(b), nil
}

// TestStreamingRoundTrip100MB encrypts and decrypts 100 MB through a pipe and
// checks the plaintext hash and that heap usage stays bounded.
func TestStreamingRoundTrip100MB(t *testing.T) {
	if testing.Short() {
		t.Skip("large payload test skipped in -short mode")
	}
	const payloadSize = 100 << 20
	const maxHeapGrowth = 16 << 20

	id, r := genKey(t)
	enc, _ := NewX25519Encryptor([]string{r})
	dec, _ := NewDecryptor(DecryptorConfig{Identity: id})

	runtime.GC()
	var before runtime.MemStats
	runtime.ReadMemStats(&before)

	wantHash := sha256.New()
	pr, pw := io.Pipe()
	done := make(chan error, 1)
	go func() {
		w, err := enc.Encrypt(pw)
		if err == nil {
			_, err = io.Copy(w, &patternSource{remaining: payloadSize, hash: wantHash})
		}
		if err == nil {
			err = w.Close()
		}
		_ = pw.CloseWithError(err)
		done <- err
	}()

	plain, err := dec.Decrypt(pr)
	if err != nil {
		t.Fatalf("Decrypt: %v", err)
	}
	gotHash := sha256.New()
	buf := make([]byte, 32*1024)
	var total, sinceSample int64
	var peak uint64
	var ms runtime.MemStats
	for {
		n, readErr := plain.Read(buf)
		_, _ = gotHash.Write(buf[:n])
		total += int64(n)
		if sinceSample += int64(n); sinceSample >= 8<<20 {
			sinceSample = 0
			runtime.ReadMemStats(&ms)
			peak = max(peak, ms.HeapInuse)
		}
		if errors.Is(readErr, io.EOF) {
			break
		}
		if readErr != nil {
			t.Fatalf("read: %v", readErr)
		}
	}
	if err := <-done; err != nil {
		t.Fatalf("encrypt: %v", err)
	}
	if total != payloadSize || !bytes.Equal(gotHash.Sum(nil), wantHash.Sum(nil)) {
		t.Fatalf("decrypted %d bytes with a different hash; want %d identical bytes", total, payloadSize)
	}
	if peak > before.HeapInuse && peak-before.HeapInuse > maxHeapGrowth {
		t.Fatalf("heap grew by %d MiB while streaming %d MiB; the stream is being buffered",
			(peak-before.HeapInuse)>>20, payloadSize>>20)
	}
}

// TestDecryptWithoutMatchingKey covers every way the configured key can miss.
func TestDecryptWithoutMatchingKey(t *testing.T) {
	_, r1 := genKey(t)
	_, r2 := genKey(t)
	w1, _ := genKey(t)
	w2, _ := genKey(t)
	x25519, _ := NewX25519Encryptor([]string{r1, r2})
	scrypt, _ := NewScryptEncryptor("the real passphrase", testWorkFactor)
	xCT := encrypt(t, x25519, []byte("x25519 archive"))
	sCT := encrypt(t, scrypt, []byte("scrypt archive"))

	cases := []struct {
		name string
		cfg  DecryptorConfig
		ct   []byte
	}{
		{"several wrong identities", DecryptorConfig{Identity: w1 + "\n" + w2}, xCT},
		{"passphrase only for an x25519 backup", DecryptorConfig{Passphrase: "the real passphrase"}, xCT},
		{"identity only for a passphrase backup", DecryptorConfig{Identity: w1}, sCT},
		{"wrong passphrases", DecryptorConfig{Passphrase: "nope", Passphrases: []string{"still nope"}}, sCT},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			dec, err := NewDecryptor(tc.cfg)
			if err != nil {
				t.Fatal(err)
			}
			_, err = dec.Decrypt(bytes.NewReader(tc.ct))
			if !errors.Is(err, ErrDecryptionFailed) {
				t.Fatalf("Decrypt = %v; want ErrDecryptionFailed before any plaintext", err)
			}
			for _, secret := range []string{w1, w2, "the real passphrase", "still nope"} {
				if strings.Contains(err.Error(), secret) {
					t.Fatal("the error leaks key material")
				}
			}
		})
	}

	// A retired passphrase listed after the current one still opens old backups.
	dec, _ := NewDecryptor(DecryptorConfig{Passphrase: "the new passphrase", Passphrases: []string{"the real passphrase"}})
	if got, err := decrypt(dec, sCT); err != nil || string(got) != "scrypt archive" {
		t.Fatalf("retired passphrase: %q, %v", got, err)
	}
}

// TestTamperedCiphertextNeverYieldsFullPlaintext flips a bit in every region of
// the file and cuts it at several offsets: each variant must fail with
// ErrDecryptionFailed, never return the complete plaintext.
func TestTamperedCiphertextNeverYieldsFullPlaintext(t *testing.T) {
	id, r := genKey(t)
	enc, _ := NewX25519Encryptor([]string{r})
	payload := randomPayload(t, 2*ageChunkSize+100)
	ct := encrypt(t, enc, payload)
	dec, _ := NewDecryptor(DecryptorConfig{Identity: id})

	macLine := bytes.Index(ct, []byte("\n--- ")) + 1
	headerEnd := macLine + bytes.IndexByte(ct[macLine:], '\n') + 1
	stanza := bytes.Index(ct, []byte("-> X25519 "))

	flip := func(off int) []byte {
		out := bytes.Clone(ct)
		out[off] ^= 0x01
		return out
	}
	variants := map[string][]byte{
		"version line":         flip(3),
		"recipient stanza":     flip(stanza + 12),
		"stanza body":          flip(bytes.IndexByte(ct[stanza:], '\n') + stanza + 3),
		"header MAC":           flip(macLine + 6),
		"stream nonce":         flip(headerEnd + 3),
		"first chunk":          flip(headerEnd + 16 + 100),
		"first chunk tag":      flip(headerEnd + 16 + ageChunkSize + 5),
		"last chunk":           flip(len(ct) - 30),
		"last tag":             flip(len(ct) - 1),
		"trailing garbage":     append(bytes.Clone(ct), "extra"...),
		"cut in header":        ct[:macLine],
		"cut before nonce end": ct[:headerEnd+8],
		"cut at chunk end":     ct[:headerEnd+16+ageChunkSize+16],
		"cut one byte short":   ct[:len(ct)-1],
		"empty":                {},
	}
	for name, v := range variants {
		t.Run(name, func(t *testing.T) {
			got, err := decrypt(dec, v)
			if !errors.Is(err, ErrDecryptionFailed) {
				t.Fatalf("decrypt = %d bytes, %v; want ErrDecryptionFailed", len(got), err)
			}
			if bytes.Equal(got, payload) {
				t.Fatal("tampered ciphertext returned the full plaintext")
			}
		})
	}
}

// TestIdentityFileFormats covers identity files as operators produce them.
func TestIdentityFileFormats(t *testing.T) {
	id, r := genKey(t)
	enc, _ := NewX25519Encryptor([]string{r})
	ct := encrypt(t, enc, []byte("payload"))
	dir := t.TempDir()
	write := func(name, content string) string {
		t.Helper()
		p := filepath.Join(dir, name)
		if err := os.WriteFile(p, []byte(content), 0o600); err != nil {
			t.Fatal(err)
		}
		return p
	}

	valid := map[string]string{
		"age-keygen output": "# created: 2026-09-24T10:00:00Z\n# public key: " + r + "\n" + id + "\n",
		"CRLF line endings": "# created: 2026-09-24T10:00:00Z\r\n" + id + "\r\n",
		"UTF-8 BOM":         "\ufeff" + id + "\n",
		"BOM and comment":   "\ufeff# public key: " + r + "\n" + id,
		"no final newline":  id,
		"indented":          "   " + id + "  \n",
	}
	for name, content := range valid {
		t.Run(name, func(t *testing.T) {
			dec, err := NewDecryptor(DecryptorConfig{IdentityFile: write(strings.ReplaceAll(name, " ", "_"), content)})
			if err != nil {
				t.Fatalf("NewDecryptor: %v", err)
			}
			if got, err := decrypt(dec, ct); err != nil || string(got) != "payload" {
				t.Fatalf("decrypt = %q, %v", got, err)
			}
		})
	}

	invalid := map[string]string{
		"public key instead of the private key": r + "\n",
		"lower-case key":                        strings.ToLower(id) + "\n",
		"truncated key":                         id[:len(id)-4] + "\n",
		"armored ciphertext":                    "-----BEGIN AGE ENCRYPTED FILE-----\n",
		"line longer than the scanner buffer":   strings.Repeat("A", 70*1024) + "\n",
		"empty file":                            "",
	}
	for name, content := range invalid {
		t.Run(name, func(t *testing.T) {
			_, err := NewDecryptor(DecryptorConfig{IdentityFile: write(strings.ReplaceAll(name, " ", "_"), content)})
			if !errors.Is(err, ErrInvalidIdentity) {
				t.Fatalf("NewDecryptor = %v; want ErrInvalidIdentity", err)
			}
			keyBody := id[len("AGE-SECRET-KEY-1"):][:16]
			if strings.Contains(err.Error(), r) || strings.Contains(strings.ToUpper(err.Error()), keyBody) {
				t.Fatal("the error echoes key material")
			}
		})
	}

	t.Run("directory", func(t *testing.T) {
		if _, err := NewDecryptor(DecryptorConfig{IdentityFile: dir, Logger: slog.New(slog.DiscardHandler)}); !errors.Is(err, ErrInvalidIdentity) {
			t.Fatalf("NewDecryptor(dir) = %v; want ErrInvalidIdentity", err)
		}
	})
	t.Run("unreadable", func(t *testing.T) {
		if runtime.GOOS == "windows" || os.Geteuid() == 0 {
			t.Skip("POSIX permissions not enforced")
		}
		p := write("unreadable", id+"\n")
		if err := os.Chmod(p, 0o000); err != nil {
			t.Fatal(err)
		}
		if _, err := NewDecryptor(DecryptorConfig{IdentityFile: p}); !errors.Is(err, ErrInvalidIdentity) || !errors.Is(err, os.ErrPermission) {
			t.Fatalf("NewDecryptor(unreadable) = %v; want ErrInvalidIdentity wrapping a permission error", err)
		}
	})
}

// TestIdentityRecipientsMatchesEncryption checks that the recipients derived from an
// identity (as the dashboard shows them) encrypt to that identity.
func TestIdentityRecipientsMatchesEncryption(t *testing.T) {
	id1, r1 := genKey(t)
	id2, r2 := genKey(t)
	got, err := IdentityRecipients("# comment\n" + id1 + "\n\n" + id2 + "\n")
	if err != nil || len(got) != 2 || got[0] != r1 || got[1] != r2 {
		t.Fatalf("IdentityRecipients = %v, %v; want [%s %s]", got, err, r1, r2)
	}
	parsed, err := age.ParseX25519Identity(id2)
	if err != nil || parsed.Recipient().String() != r2 {
		t.Fatalf("GenerateX25519 pair mismatch: %v", err)
	}
}
