package secretbox

import (
	"errors"
	"fmt"
	"io/fs"
	"log/slog"
	"os"
	"path/filepath"
	"runtime"
)

// KeyFileName is the auto-generated key file inside the data directory.
const KeyFileName = "secret.key"

// keyFileMode is the permission of a generated key file.
const keyFileMode fs.FileMode = 0o600

// KeySource describes where the key comes from; see LoadKey.
type KeySource struct {
	// Env is the base64 key from MONGORESCUE_SECRET_KEY; it wins when set.
	Env string
	// File is the key file used (and created on first start) when Env is empty.
	File string
}

// LoadedKey is the result of LoadKey.
type LoadedKey struct {
	// Key is the raw key.
	Key []byte
	// Created reports that File did not exist and was generated by this call. A caller
	// that then fails to open the database with it should remove the file again.
	Created bool
	// FromEnv reports that the key came from KeySource.Env.
	FromEnv bool
}

// LoadKey returns the configured key: KeySource.Env when set, else the content of
// KeySource.File, generating a new random key there on first start. The file is
// written atomically (temporary file, fsync, rename) with mode 0600; an existing file
// readable by group or others only triggers a warning. Key material is never logged.
func LoadKey(src KeySource, logger *slog.Logger) (*LoadedKey, error) {
	if logger == nil {
		logger = slog.Default()
	}
	if src.Env != "" {
		key, err := ParseKey(src.Env)
		if err != nil {
			return nil, fmt.Errorf("MONGORESCUE_SECRET_KEY: %w", err)
		}
		return &LoadedKey{Key: key, FromEnv: true}, nil
	}
	if src.File == "" {
		return nil, errors.New("secretbox: no key source configured")
	}

	content, err := os.ReadFile(src.File)
	switch {
	case err == nil:
		warnLoosePermissions(src.File, logger)
		key, perr := ParseKey(string(content))
		if perr != nil {
			return nil, fmt.Errorf("%s: %w", src.File, perr)
		}
		return &LoadedKey{Key: key}, nil
	case !errors.Is(err, fs.ErrNotExist):
		return nil, fmt.Errorf("secretbox: read key file: %w", err)
	}

	key, err := GenerateKey()
	if err != nil {
		return nil, err
	}
	if err := writeFileAtomic(src.File, []byte(EncodeKey(key)+"\n")); err != nil {
		return nil, err
	}
	logger.Info("generated a new secret key for credentials at rest; keep a copy of it, stored separately from database backups",
		slog.String("path", src.File))
	return &LoadedKey{Key: key, Created: true}, nil
}

// warnLoosePermissions logs a warning when path is readable by group or others.
func warnLoosePermissions(path string, logger *slog.Logger) {
	if runtime.GOOS == "windows" {
		return
	}
	info, err := os.Stat(path)
	if err == nil && info.Mode().Perm()&0o077 != 0 {
		logger.Warn("secret key file is accessible by group or others; restrict it with chmod 600",
			slog.String("path", path), slog.String("mode", info.Mode().Perm().String()))
	}
}

// writeFileAtomic writes data to path via a synced temporary file, a rename and a sync
// of the parent directory, so a crash never leaves a truncated key behind and a key
// that LoadKey returned survives a power loss.
func writeFileAtomic(path string, data []byte) (err error) {
	dir := filepath.Dir(path)
	if err = os.MkdirAll(dir, 0o750); err != nil {
		return fmt.Errorf("secretbox: create key directory: %w", err)
	}
	tmp, err := os.CreateTemp(dir, ".secret.key.tmp-*")
	if err != nil {
		return fmt.Errorf("secretbox: create key file: %w", err)
	}
	defer func() {
		if err != nil {
			_ = tmp.Close()
			_ = os.Remove(tmp.Name())
		}
	}()
	if runtime.GOOS != "windows" {
		if err = tmp.Chmod(keyFileMode); err != nil {
			return fmt.Errorf("secretbox: chmod key file: %w", err)
		}
	}
	if _, err = tmp.Write(data); err != nil {
		return fmt.Errorf("secretbox: write key file: %w", err)
	}
	if err = tmp.Sync(); err != nil {
		return fmt.Errorf("secretbox: sync key file: %w", err)
	}
	if err = tmp.Close(); err != nil {
		return fmt.Errorf("secretbox: close key file: %w", err)
	}
	if err = os.Rename(tmp.Name(), path); err != nil {
		return fmt.Errorf("secretbox: install key file: %w", err)
	}
	// The rename is only durable once the directory entry is: without this, a power
	// loss could lose the key after the database already recorded its check value.
	if err = syncDir(dir); err != nil {
		return fmt.Errorf("secretbox: sync key directory: %w", err)
	}
	return nil
}
